### ISSUE TITLE
2022年5月29日实测不能用了

### ISSUE THREAD

**Issue by xiamodefeiniao** [zonas0574/163musicDownload#3]
Exception in thread "main" java.lang.NullPointerException                                                                       
at zonas.API.playlist_detail(API.java:19)                                                                              
at zonas.App.main(App.java:19)  
大致猜到和其他工具是一样的问题，猪场应该是把数据加密了/更新了API，获取数据为空导致的 
gtmd猪场

**Comment by zonas0574** [comment]
我随便试歌单和单曲都可以下载，当然vip歌曲应该不行。不知道你有没有输错歌单和单曲不同接口
